### ISSUE TITLE
[Feature request] - Adjust the fee for asset (token) issuance to 150000 * FEE_QUANT from 15000 * FEE_QUANT

### ISSUE THREAD

**Issue by paulpoco** [signum-network/SIPs#37]
Adjust the fee for asset (token) issuance to 150000 * FEE_QUANT from 15000 * FEE_QUANT

Currently the token creation is being abused by bad actors with offensive names and illegal acts and sending them to people unsolicited.  It wasn't abused before the token issuance fee was lowered.

This causes a bad name for SIGNUM.  And will drive people away.

Here are some names and their creators, not all offensive but some are the same as real coins past and present.
![image](https://user-images.githubusercontent.com/801414/145723304-594ca4d2-1c7c-41fc-8763-92cff81297a5.png)
![image](https://user-images.githubusercontent.com/801414/145723313-b5e38ef3-d149-4f29-965b-6c3070445a95.png)
![image](https://user-images.githubusercontent.com/801414/145723336-72f4ab83-1d50-431d-a4b6-846b86453b2c.png)

Not sure what the one that starts with Y even means.

**Comment by frankTheTank72** [comment]
Yes we are an open blockchain and ppl do such things - nobody likes.
But any fee adjustment is not the solution. We need to block those names on the explorer as we do already here https://chain.signum.network/ and we should change the behaviour on our wallets only to show tokesn which you are active selected as it is done on any other chain. BTDEX is already doing  that amd we are looking into a solution for Phoenix

**Comment by ohager** [comment]
I agree on the free and open platform, although I don't like morally disillusioned attitude. IMHO, we should solve this on application level and not protocol level. In the end it is the majority/community who regulates "unfit" tokens and such. If we continue to discuss, blame and disregard such behavior publicly we do not give space to such individuals - our healthy community culture is the best approach. I really appreciate your concern here. But yes, we will offer ways and methods to filter out unwanted tx in our applications.

**Comment by frankTheTank72** [comment]
close this
