### ISSUE TITLE
Fearure Request NFT:  add tokens and SIGNA flow to owner

### ISSUE THREAD

**Issue by paulpoco** [signum-network/SIPs#53]
Note:  I do not know how to format for SIPS.

 Request NFT:  add tokens and SIGNA flow to owner.

1) During the NFT portal screen to add your graphic
     a) connected XT wallet would know what existing tokens the account has
     b) a drop down to show what tokens are selectable
     c) a box for how many tokens to include with NFT minting
2) Have code for the Minted NFT that when SIGNA lands in the smart contract address of the NFT that the new SIGNA gets sent to owner of the NFT.

This would be to take an existing token and include it with a unique NFT graphic that says how many tokens are included.   And when the token sends out dividends then the NFT smart contract passes the received SIGNA to the NFT owner's SIGNA address. 

Not sure about royalties or platform fees.

**Comment by rogerwim** [comment]
This should be in NFT feedback, not SIP's

**Comment by frankTheTank72** [comment]
I close the ticket please repon if still needed on https://github.com/signum-nft/feedback-signumart
