### ISSUE TITLE
SRC44 - Update the `rule` column displayed in the `alias/al` field

### ISSUE THREAD

**Issue by ipr0310** [signum-network/SIPs#89]
As the modernization of the alias framework will allow STLDs, is necessary to make update on the specifications table:
https://github.com/signum-network/SIPs/blob/master/SIP/sip-44.md#specification

As we can appreciate in the `alias` field, the `rule` column shows an outdated one, it should be a regex expression that support STLDs
![image](https://user-images.githubusercontent.com/35440957/229429590-4b5d46f7-399d-4e13-abb5-b7fae884cb4e.png)

**Testing the expression**
![image](https://user-images.githubusercontent.com/35440957/229430342-3e98ccba-9b46-4703-8d3e-2bff43603bac.png)

**Solution**
The regex expression can be updated to the following:
```
^(\w+)(?:\.(\w+))?$
```

**Testing the expression**
![image](https://user-images.githubusercontent.com/35440957/229430726-76eddd0f-b095-4bce-b839-b6b635db7a19.png)

**Additional context**
According to devina.io redos-checker
It states that the statement is safe
![image](https://user-images.githubusercontent.com/35440957/229430913-7f08f145-186a-4ab4-af83-46a41ab232d9.png)

**Comment by ohager** [comment]
closing.... there was a pending PR that was not merge
